/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ucla_nesl_android_ashmem_datareceiver_nativelib_NativeLib */

#ifndef _Included_edu_ucla_nesl_android_ashmem_datareceiver_nativelib_NativeLib
#define _Included_edu_ucla_nesl_android_ashmem_datareceiver_nativelib_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ucla_nesl_android_ashmem_datareceiver_nativelib_NativeLib
 * Method:    setFD
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_ucla_nesl_android_ashmem_datareceiver_nativelib_NativeLib_setFD
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_ucla_nesl_android_ashmem_datareceiver_nativelib_NativeLib
 * Method:    readFromFD
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_ucla_nesl_android_ashmem_datareceiver_nativelib_NativeLib_readFromFD
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_ucla_nesl_android_ashmem_datareceiver_nativelib_NativeLib
 * Method:    closeFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_ucla_nesl_android_ashmem_datareceiver_nativelib_NativeLib_closeFD
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
