/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marakana_android_fibonaccinative_FibLib */

#ifndef _Included_com_marakana_android_fibonaccinative_FibLib
#define _Included_com_marakana_android_fibonaccinative_FibLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_marakana_android_fibonaccinative_FibLib
 * Method:    fibNR
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL com_marakana_android_fibonacciclientnative_FibLib_fibNR
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_marakana_android_fibonaccinative_FibLib
 * Method:    fibNI
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL com_marakana_android_fibonacciclientnative_FibLib_fibNI
  (JNIEnv *, jclass, jlong);

jint JNICALL com_marakana_android_fibonacciclientnative_FibLib_SetDataFD
(JNIEnv * env, jclass jthis, jint fd)

#ifdef __cplusplus
}
#endif
#endif
