/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marakana_android_fibonacciclientnative_FibLibClient */

#ifndef _Included_com_marakana_android_fibonacciclientnative_FibLibClient
#define _Included_com_marakana_android_fibonacciclientnative_FibLibClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_marakana_android_fibonacciclientnative_FibLibClient
 * Method:    fibNR
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_marakana_android_fibonacciclientnative_FibLibClient_fibNR
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_marakana_android_fibonacciclientnative_FibLibClient
 * Method:    fibNI
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_marakana_android_fibonacciclientnative_FibLibClient_fibNI
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_marakana_android_fibonacciclientnative_FibLibClient
 * Method:    SetDataFD
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_marakana_android_fibonacciclientnative_FibLibClient_SetDataFD
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_marakana_android_fibonacciclientnative_FibLibClient
 * Method:    ReadDataFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_marakana_android_fibonacciclientnative_FibLibClient_ReadDataFD
  (JNIEnv *, jclass);

/*
 * Class:     com_marakana_android_fibonacciclientnative_FibLibClient
 * Method:    CloseFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_marakana_android_fibonacciclientnative_FibLibClient_CloseFD
  (JNIEnv *, jclass);

/*
 * Class:     com_marakana_android_fibonacciclientnative_FibLibClient
 * Method:    GetStringFD
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_marakana_android_fibonacciclientnative_FibLibClient_GetStringFD
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
