/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marakana_android_fibonaccinative_FibLib */

#ifndef _Included_com_marakana_android_fibonaccinative_FibLib
#define _Included_com_marakana_android_fibonaccinative_FibLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_marakana_android_fibonaccinative_FibLib
 * Method:    fibNR
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_marakana_android_fibonaccinative_FibLib_fibNR
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_marakana_android_fibonaccinative_FibLib
 * Method:    fibNI
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_marakana_android_fibonaccinative_FibLib_fibNI
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_marakana_android_fibonaccinative_FibLib
 * Method:    getTestFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_marakana_android_fibonaccinative_FibLib_getTestFD
  (JNIEnv *, jclass);

/*
 * Class:     com_marakana_android_fibonaccinative_FibLib
 * Method:    writeToFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_marakana_android_fibonaccinative_FibLib_writeToFD
  (JNIEnv *, jclass);

/*
 * Class:     com_marakana_android_fibonaccinative_FibLib
 * Method:    CloseFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_marakana_android_fibonaccinative_FibLib_CloseFD
  (JNIEnv *, jclass);

/*
 * Class:     com_marakana_android_fibonaccinative_FibLib
 * Method:    CreateDataFD
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_marakana_android_fibonaccinative_FibLib_CreateDataFD
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
